### ISSUE TITLE
Using own campaign file

### ISSUE THREAD

**Issue by kensinghton** [AaronGullickson/mekhq-blog#5]
```
axeller@BANSHEE:/idea/mekhq-blog$ python3.8 ./process_campaign.py
Traceback (most recent call last):
  File "./process_campaign.py", line 551, in <module>
    role_name = get_person_role(primary_role)
  File "./process_campaign.py", line 175, in get_person_role
    return roles_dict[role]
KeyError: '1'
```
Tried importing my own campaing with no success.
Campaign file: 
[https://fex.net/uk/s/9semtac](https://fex.net/uk/s/9semtac)

**Comment by AaronGullickson** [comment]
Yes, this usually requires some updating with newer versions of MHQ. It looks like you are on 49.7 and my guess is that personnel roles got the `enum` treatment. I will try to take a look at it soon and update.

**Comment by AaronGullickson** [comment]
I can't seem to access your files anymore to check things. I did update my own campaign to MekHQ 0.49.7 and it worked fine with the latest development version so I think the issue you are having is from an earlier version having to do with the change to personnel type enums. I just made a new release available (v0.3). Please try that and let me know if it does not work for you.

**Comment by AaronGullickson** [comment]
@kensinghton Let me know if this works for you when you get a chance, please.

**Comment by AaronGullickson** [comment]
Closing this for a lack of response.
